### ISSUE TITLE
Automatic deprecation shutdown feature. How do I get rid of it? If there is no upgrade?

### ISSUE THREAD

**Issue by neurans** [MyHush/hush#50]
This issue tracker is only for technical issues related to hushd, the Hush node daemon.

General Hush questions and/or support requests and are best directed to the [Hush Forums](https://forum.myhush.org) or [Slack Chat](https://myhush.slack.com).

For reporting security vulnerabilities or for sensitive discussions with our security team, please contact your local nasal demon via ICMP.

### Describe the issue
Automatic deprecation shutdown feature. How do I get rid of it? If there is no upgrade? Is there a quick upgrade ?

Messages:
- Warning: This version will be deprecated at block height 193076, and will automatically shut down. You should upgrade to the latest version of
  Zcash. To disable deprecation for this version, set -disabledeprecation=1.0.9.

**Comment by madbuda** [comment]
this feature is not enabled in the current hush release (1.0.9) and the message can safely be ignored.

If you'd like to not see this msg put 
`disabledeprecation=1.0.9`
in your hush.conf or in your startup command as the message states

**Comment by radix42** [comment]
There is a command line switch to turn the feature off...what block height
are we at now?

**Comment by madbuda** [comment]
@radix42 185929

**Comment by radix42** [comment]
so we have just over 12 days to get 1.0.12 out the door....less, because
that's when auto-senesence sets in. Damnit I forgot to take the feature
out, or do the build with it disabled for Windows, or change the block
height to be farther in the future. I am going to disable this in 1.0.12.
What's the best branch to start with? do we have a release candidate yet?
I'd rather nobody have to rebase if we can avoid it :-)

**Comment by madbuda** [comment]
@radix42 https://github.com/MyHush/hush/tree/v1.0.12-rc

**Comment by radix42** [comment]
thank you......have me merged the testnet code into the RC yet?

**Comment by madbuda** [comment]
🤔  I don't remember, if not I'll do it tonight
